language: node_js
node_js:
  - "10"
dist: trusty # needs Ubuntu Trusty
sudo: false  # no need for virtualization.
before_install:
  - npm install -g npm@latest
install:
  - npm config set package-lock false
  - npm install
sudo: required
addons:
  chrome: stable # install chrome stable.
cache:
  yarn: true
  directories:
    - $HOME/.npm
before_script:
  - bash ./config/deploy-nightly.sh setup
  - npm run lint
script:
  - npm run coverage
after_success:
  - bash ./config/deploy-nightly.sh build
