language: node_js
node_js:
  - "8"
dist: trusty # needs Ubuntu Trusty
sudo: false  # no need for virtualization.
before_install:
  - npm install -g npm@latest
install:
  - npm install
sudo: required
addons:
  chrome: stable # install chrome stable.
cache:
  yarn: true
  directories:
    - $HOME/.npm
before_script:
  - npm run lint
  - git config --global user.email 'travis@travis-ci.org' &&  git config --global user.name 'Travis CI'
  # - git fetch origin && git checkout nightly && git merge origin/master --no-verify
  - npm run deploy:nightly
  - git remote add upstream https://$GH_TOKEN@github.com/naver/billboard.js.git > /dev/null 2>&1
  - git push upstream nightly
script:
  # - npm run coverage
  # - npm run deploy:nightly
after_success:
  # - git remote add upstream https://$GH_TOKEN@github.com/naver/billboard.js.git > /dev/null 2>&1
  # - git push upstream nightly
