language: node_js
node_js:
  - "8"
dist: trusty # needs Ubuntu Trusty
sudo: false  # no need for virtualization.
before_install:
  - npm install -g npm@latest
install:
  - npm install
sudo: required
addons:
  chrome: stable # install chrome stable.
cache:
  yarn: true
  directories:
    - $HOME/.npm
before_script:
  - npm run lint
script:
  - npm run coverage
  - npm run deploy:nightly
after_success:
  - git remote show origin
  - git branch
  - git push origin nightly