language: node_js
node_js:
  - "8"
dist: trusty # needs Ubuntu Trusty
sudo: false  # no need for virtualization.
before_install:
  - npm install -g npm@latest
install:
  - npm install
sudo: required
addons:
  chrome: stable # install chrome stable.
cache:
  yarn: true
  directories:
    - $HOME/.npm
before_script:
  - git fetch --all --prune
  - git checkout nightly
  - git merge origin/master
  - npm run lint
script:
  - npm run coverage
after_success:
  - sh ./config/deploy-nightly.sh
  