language: node_js
node_js:
  - "10"
dist: trusty # needs Ubuntu Trusty
sudo: false  # no need for virtualization.

before_install:
  - npm install -g npm@latest
install:
  - npm config set package-lock false
  - npm install

cache:
  yarn: true
  npm: true
  directories:
    - $HOME/.npm

stages:
  - lint
  - test
  - release

jobs:
  include:
    - stage: lint
      script:
        - bash ./config/deploy-nightly.sh setup
        - npm run lint
    - stage: test
      sudo: required
      addons:
        chrome: stable # install chrome stable.
      script:
        - npm run coverage
      after_success:
        - npm run coveralls
    - stage: release
      script:
        - bash ./config/deploy-nightly.sh build
