name: Release
on:
  workflow_run:
    workflows: ["CI"]
    branches: [latest, next]
    types:
      - completed

# https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/github-actions.md
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm config set package-lock false
          npm install

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        id: publish
        run: npm run release
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        # https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions
        # if: contains('refs/heads/next refs/heads/latest', github.ref)      

      - name: Deploy
        run: bash ./config/deploy.sh
        if: steps.publish.outputs.branch == 'latest' && steps.publish.outputs.conclusion == 'success'
